### ISSUE TITLE
FYI: ArchLinux packages available

### ISSUE THREAD

**Issue by UffeJakobsen** [emartisoft/IDE65XX#1]
This is not an issue - just FYI

AUR (ArchLinux User Repository) packages available:

Stable (versioned) package
https://aur.archlinux.org/packages/ide65xx/

Unstalbe  (bleeding edge) (master branch) package
https://aur.archlinux.org/packages/ide65xx-git/

In case you wonder - uppercase letters are not allowed in package names - that goes for at lot of distributions

**Comment by emartisoft** [comment]
Thank you. I will use lowercase for next versions.
