### ISSUE TITLE
VICE (x64) closes with error after compile & run

### ISSUE THREAD

**Issue by SCWinde** [emartisoft/IDE65XX#10]
When I do Compile & Run, IDE65XX launches VICE and loads my code.
When I close X64.app (on OSX) I get an error.

I have the same setup in Relaunch64, this does not produce errors when closing X64, so I figure it has to do with the way IDE65XX launches X64.

**Comment by emartisoft** [comment]
You must not select X64 (without app extension file in folder bin). You must select X64sc.App. I have not X64.app in my VICE folder.
<a href="https://ibb.co/gPkkcCN"><img src="https://i.ibb.co/RBRRJWf/Screen-Shot-2020-06-01-at-01-40-14.png" alt="Screen-Shot-2020-06-01-at-01-40-14" border="0"></a>

**Comment by SCWinde** [comment]
Makes no difference: they both give an 'unexpected error' when I close them.
They don't do that when I open them directly and then close them. It only happens when starting the up from IDE 65XX.

**Comment by emartisoft** [comment]
May you write emulator parameter and emulator path from settings. Which VICE use? I am using SDL based VICE.

**Comment by SCWinde** [comment]
It was v3.1 GTK.
Path was "/Applications/C64/VICE/x64sc.app/Contents/MacOS/x64sc"
Emulator parameter is <file>.
 
I upgraded to v3.4 SDL, problem solved: it can be closed without errors.
Thanks.
