### ISSUE TITLE
Missing exit shortcut ala CTRL-Q

### ISSUE THREAD

**Issue by UffeJakobsen** [emartisoft/IDE65XX#2]

**Comment by emartisoft** [comment]
No exit shorcut. CTRL-Q defined for comment on text line.

**Comment by UffeJakobsen** [comment]
Well that is an unfortunate collision - I hope that the shortcut keys will be redefinable at some point :-)

**Comment by UffeJakobsen** [comment]
How about ALT-X or ALT-Q a exit/quit shortcut then ? that seems to be the second choise for linux GUI apps

**Comment by emartisoft** [comment]
I'll define ALT + X to close/exit app for you.
