### ISSUE TITLE
Desktop font is too small

### ISSUE THREAD

**Issue by UffeJakobsen** [emartisoft/IDE65XX#3]
The used desktop font (not the editor font) is too small to read on a large screen

**Comment by emartisoft** [comment]
You may change font family or size from settings menu.

Settings/General/Application Font or Code Editor Font

**Comment by UffeJakobsen** [comment]
Ah missed that one - mostly because the rezise and scrolling of the setting window is a little broken (I know it is an early beta)

Thanks :+1:
