### ISSUE TITLE
desktop file/icon (freedesktop compatible) for distributions

### ISSUE THREAD

**Issue by UffeJakobsen** [emartisoft/IDE65XX#4]
It would be nice with a (freedesktop compatible) desktop file/icon for distributions

https://wiki.archlinux.org/index.php/desktop_entries

**Comment by emartisoft** [comment]
You are right. I am using _Ubuntu_ 20. for Linux, I created installer file by _CQtDeployer_. I am not sure but I think that _CQtDeployer_ does not use **/usr/share/icons** or **/usr/share/applications** folders. But _Ubuntu_ displays **IDE65XX** shorcut icon on Show Applications Menu.

Did you install this app via InstallerIDE65xx_0.1Beta_Linux.run? Or compile from source code?

**Comment by UffeJakobsen** [comment]
> Did you install this app via InstallerIDE65xx_0.1Beta_Linux.run? Or compile from source code?

As I maintain the AUR packages I compile from source - and it would be nice if the compiled AUR packages also installed a freedesktop file and icon. 
Of course I could make a desktop file/icon my self - but I guess that you have some kind of logo in mind ?

**Comment by emartisoft** [comment]
It may be 256x256 PNG icon from _https://github.com/emartisoft/IDE65XX/tree/master/icon_

If provided that icon and script file are in the same directory, the following commands can be run. (If app path is /usr/bin)

```bash
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "This script must be run as root"
    exit
fi
echo "[Desktop Entry]
Name=IDE 65XX
Comment=IDE 65XX Kick Assembler Edition
Exec=/usr/bin/IDE65xx
Icon=ide65xx.png
Terminal=false
Type=Application
X-Ubuntu-Touch=true" > 'IDE 65XX.desktop'

cp ide65xx.png /usr/share/icons
cp 'IDE 65XX.desktop' /usr/share/applications
```

**Comment by emartisoft** [comment]
I also installed ArchLinux for the first time. I installed IDE65XX from github release (InstallerIDE65xx_0.1Beta_Linux.tar.xz). it displays in the show applications menu.

**Comment by UffeJakobsen** [comment]
Well my request was really about making easy and identical packages to different (freedesktop compatible) distributions.
So that every distribution packager (like me) do not have to invent the wheel himself.

Putting the "IDE65XX.desktop" file into your repository would allow every distribution packager to use the desktop file - and not having to create it :-)
