### ISSUE TITLE
Choice between using tabs or any no. of spaces for TAB

### ISSUE THREAD

**Issue by SCWinde** [emartisoft/IDE65XX#5]
Please build in to be able to choose either tabs or any given number of spaces when pressing TAB.
Of course, auto-indent should continue with that setting too.

**Comment by emartisoft** [comment]
You wanna change space value for TAB key from settings?

**Comment by SCWinde** [comment]
What I mean is that I want to be able to choose between using tabs or using individual spaces.

**Comment by emartisoft** [comment]
for example: If you wanna load a file that includes char tabs. But You do not wanna char tab. You wanna convert from char tab to char space. In addition, space must be tab size.

**Comment by SCWinde** [comment]
Hmm, not sure what to do with files that already have tabs, but setting is in chars.
I'd say conversion to spaces would be nice.
But what if you have spaces only and setting is tab, then how would the computer know the intended tab-size of the file?
This could be a setting too: convert file yes/no?

**Comment by emartisoft** [comment]
Tab size is customizable. IDE65XX has it in settings. Some editors convert char tabs to spaces irreversibly. If your settings is checked to true for this property, It does not ask user and does it.

**Comment by SCWinde** [comment]
I'm a space user, I could live with irreversible conversion from tab to spaces.

**Comment by emartisoft** [comment]
Ok, I am implementing...

**Comment by emartisoft** [comment]
it is ready for version 0.1.3 but not released
